config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/" => "home#index"

  resources :todos

  resources :users

  post "users/login", to: "users#login"

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true
  belongs_to :user

  def self.of_user(user)
    all.where(user_id: user.id)
  end

  def self.overdue
    all.where("due_date < ? and (not completed)", Date.today)
  end

  def self.due_today
    all.where("due_date = ?", Date.today)
  end

  def self.due_later
    all.where("due_date > ?", Date.today)
  end

  def self.completed
    all.where(completed: true)
  end

  def self.remaining
    all.where(completed: false)
  end

  def to_pleasant_string
    "#{id}. #{due_date.to_s} #{todo_text} #{completed ? "[X]" : "[ ]"}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :first_name, length: { minimum: 2 }
  validates :email, presence: true
  validates :password, presence: true
  validates :password, length: { minimum: 6 }

  has_secure_password
  has_many :todos

  def to_pleasant_string
    "#{id}. #{name} #{email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id

      redirect_to "/"
    else
      flash[:error] = "Your login attempt was invalid.Please retry"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    render plain: todo.to_pleasant_string
  end

  def create
    todo_text = params[:todo_text]
    user_id = current_user.id
    due_date = DateTime.parse(params[:due_date])
    new_todo = Todo.new({
      todo_text: todo_text,
      due_date: due_date,
      user_id: user_id,
      completed: false,
    })
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = Todo.of_user(current_user).find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render plain: User.all.map { |user| user.to_pleasant_string }.join("\n")
  end

  def new
    render "users/new"
  end

  def create
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    password = params[:password]

    new_user = User.new({
      first_name: first_name,
      last_name: last_name,
      email: email,
      password: password,
    })
    if new_user.save
      flash[:success] = "you've signed-up successfully, now please sign-in to continue"
      redirect_to new_sessions_path
    else
      flash[:error] = new_user.errors.full_messages.join("|")
      redirect_to new_user_path
    end
  end

  def login
    email = params[:email]
    password = params[:password]

    user = User.find_by email: email
    render plain: user ? isValidPassword(password, user.password) : false
  end

  def isValidPassword(password, hashedPassword)
    password == hashedPassword
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<main class="Container">
  <h1 class="Home-heading">Welcome to To-do Manager</h1>

  <h3 class="Home-text" >If you are new user <%= link_to "Sign up here", new_user_path %></h3>
  <h3 class="Home-text">If you are existing user <%= link_to "Sign-in here", new_sessions_path %></h3>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"
    />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %> 
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    
  </head>

  <body>
    <% if @current_user %>
    <header class="UserHeader">
      <h1 class="UserHeader-name">Welcome <%= @current_user.first_name %></h1>
      <%= link_to "Sign-Out", destroy_session_path, method: "delete", class: "UserHeader-signOut" %>
    </header>
    <% end %> 
    <% if flash[:error] %>
      <div class="Container">
      <ul class="FlashContainer">
        <% flash[:error].split("|").each do |err| %>
          <li class="Error" >
            <%= err %>
          </li>
        <% end %>
      </ul>
      </div>
    <% end %>
    <% if flash[:success] %>
      <div class="Container">
      <ul class="FlashContainer">
        <% flash[:success].split("|").each do |err| %>
          <li class="Success" >
            <%= err %>
          </li>
        <% end %>
      </ul>
      </div>
    <% end %>
   

    <%= yield %>
    
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-text"><%= section_title %></p>
    <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count %>/<%= todos.count %></p>
  </div>
  <ul class="TodoItem-container">
    <% todos.each do |todo| %>
      <li class="TodoItem">
        <%= form_with(url: "todos/#{todo.id}", method: "put") do %>
          <input 
            type="checkbox" 
            class="TodoItem-checkbox" 
            name="completed"  
            onclick="this.form.submit()"
            <%= todo.completed ? "checked" : nil %>
          />
        <% end %>
        <span class=<%= todo.completed ? "TodoItem-completed" : "" %>  >
          <%= todo.todo_text %>
        </span>
        <% if show_due_date %>
          <p class="TodoItem-date"><%= todo.due_date.to_s(:short) %></p>
        <% end %>
        <a href="javascript:void(0)" class="TodoItem-delete">
          <%= form_with(url: "todos/#{todo.id}", method: "delete") do %>
            <input type='image' class="TodoItem-delete-icon" src="./trash.svg" alt="submit" />
          <% end %>
        </a>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<main class="Container">
  <article>
    <h1 class="Todopage-title">My To-do List</h1>
    <%= form_with(url: "todos", method: "post", class: "AddTodo") do %>
      <%= text_field_tag "todo_text", nil, class: "Form-input AddTodo-text", placeholder: "What's Nex" %>
      <input
        type="date"
        class="Form-input AddTodo-date"
        name="due_date"
        required
      />
      <input type="submit" class="Btn Btn-primary" value="Add" />
    <% end %>
    <%= render partial: "todo-section", locals: { section_title: "Overdue", todos: @todos.overdue, show_due_date: true } %>
    <%= render partial: "todo-section", locals: { section_title: "Due Today", todos: @todos.due_today, show_due_date: false } %>
    <%= render partial: "todo-section", locals: { section_title: "Due Later", todos: @todos.due_later, show_due_date: true } %>
  </article>
</main>

app/views/users/new.html.erb
<main class="Container UserMainPage">
  <section class= "UserNew">
  <p class="UserNew-title" >Welcome New User</p>
    <%= form_with url: users_path do |form| %>
      <div class="Form-section" >
        <p class="Form-label" >First Name :</p>
        <%= form.text_field :first_name, class: "Form-input User-input" %>
      </div>
      <div class="Form-section" >
        <p class="Form-label" >Last Name :</p>
        <%= form.text_field :last_name, class: "Form-input User-input" %>
      </div>
      <div class="Form-section" >
        <p class="Form-label" >Email :</p>
        <%= form.email_field :email, class: "Form-input User-input" %>
      </div>
      <div class="Form-section" >
        <p class="Form-label" >Password :</p>
        <%= form.password_field :password, class: "Form-input User-input" %>
      </div>
      <div class="Form-section" >
        <%= form.submit "Sign Up!", class: "Btn Btn-primary User-submit" %>
      </div>
    <% end %>
  </section>  
</main>